name: Run Python Script

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step to set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12 # e.g., 3.8

    # Step to install dependencies from your requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run your Python script while accessing the secret API key
    - name: Run Python script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Replace with the name of your secret key in GitHub
      run: |
        python matderi_github_v0.01.py
